version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - weathernetwork
    depends_on:
      - redis
      - backend
    stdin_open: true
    tty: true
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    networks:
      - weathernetwork
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - weathernetwork
networks:
  weathernetwork:
    driver: bridge
